// Detection dictionaries for deriving a categorized tech stack from a repo.
// Keep additions here; the sync script just consumes these tables.

// GitHub "languages" API name -> [displayName, category]
export const LANG_MAP = {
  Python: ['Python', 'Language'],
  'Jupyter Notebook': ['Jupyter', 'Data'],
  TypeScript: ['TypeScript', 'Language'],
  JavaScript: ['JavaScript', 'Language'],
  HTML: ['HTML', 'Frontend'],
  CSS: ['CSS', 'Frontend'],
  SCSS: ['SCSS', 'Frontend'],
  Vue: ['Vue', 'Frontend'],
  Svelte: ['Svelte', 'Frontend'],
  Java: ['Java', 'Language'],
  Kotlin: ['Kotlin', 'Mobile'],
  Swift: ['Swift', 'Mobile'],
  Dart: ['Dart', 'Mobile'],
  Go: ['Go', 'Language'],
  Rust: ['Rust', 'Language'],
  Ruby: ['Ruby', 'Language'],
  PHP: ['PHP', 'Language'],
  'C#': ['C#', 'Language'],
  'C++': ['C++', 'Language'],
  C: ['C', 'Language'],
  R: ['R', 'Data'],
  MATLAB: ['MATLAB', 'Data'],
  Shell: ['Shell', 'DevOps'],
  Dockerfile: ['Docker', 'DevOps'],
  PLpgSQL: ['SQL', 'Database'],
  TSQL: ['SQL', 'Database'],
  SQL: ['SQL', 'Database'],
}

// Dependency / package name (npm + pip, lowercased) -> [displayName, category].
// Matching is exact on the normalized package name (extras/specifiers stripped).
export const PKG_MAP = {
  // Frontend
  react: ['React', 'Frontend'],
  next: ['Next.js', 'Frontend'],
  vue: ['Vue', 'Frontend'],
  svelte: ['Svelte', 'Frontend'],
  '@angular/core': ['Angular', 'Frontend'],
  vite: ['Vite', 'Frontend'],
  tailwindcss: ['Tailwind CSS', 'Frontend'],
  '@reduxjs/toolkit': ['Redux', 'Frontend'],
  redux: ['Redux', 'Frontend'],
  'framer-motion': ['Framer Motion', 'Frontend'],
  three: ['Three.js', 'Frontend'],
  d3: ['D3', 'Frontend'],
  'chart.js': ['Chart.js', 'Frontend'],
  bootstrap: ['Bootstrap', 'Frontend'],
  '@mui/material': ['MUI', 'Frontend'],
  streamlit: ['Streamlit', 'Frontend'],
  gradio: ['Gradio', 'Frontend'],
  // Backend
  express: ['Express', 'Backend'],
  fastify: ['Fastify', 'Backend'],
  '@nestjs/core': ['NestJS', 'Backend'],
  fastapi: ['FastAPI', 'Backend'],
  flask: ['Flask', 'Backend'],
  django: ['Django', 'Backend'],
  uvicorn: ['Uvicorn', 'Backend'],
  gunicorn: ['Gunicorn', 'Backend'],
  pydantic: ['Pydantic', 'Backend'],
  celery: ['Celery', 'Backend'],
  aiohttp: ['aiohttp', 'Backend'],
  // Database / vector stores
  'psycopg2-binary': ['PostgreSQL', 'Database'],
  psycopg2: ['PostgreSQL', 'Database'],
  psycopg: ['PostgreSQL', 'Database'],
  pg: ['PostgreSQL', 'Database'],
  pymysql: ['MySQL', 'Database'],
  mysql2: ['MySQL', 'Database'],
  mysql: ['MySQL', 'Database'],
  sqlalchemy: ['SQLAlchemy', 'Database'],
  'better-sqlite3': ['SQLite', 'Database'],
  mongoose: ['MongoDB', 'Database'],
  pymongo: ['MongoDB', 'Database'],
  redis: ['Redis', 'Database'],
  prisma: ['Prisma', 'Database'],
  chromadb: ['ChromaDB', 'Database'],
  faiss: ['FAISS', 'Database'],
  'faiss-cpu': ['FAISS', 'Database'],
  'faiss-gpu': ['FAISS', 'Database'],
  'pinecone-client': ['Pinecone', 'Database'],
  'weaviate-client': ['Weaviate', 'Database'],
  'qdrant-client': ['Qdrant', 'Database'],
  // ML / AI
  torch: ['PyTorch', 'ML / AI'],
  pytorch: ['PyTorch', 'ML / AI'],
  'pytorch-lightning': ['PyTorch Lightning', 'ML / AI'],
  tensorflow: ['TensorFlow', 'ML / AI'],
  keras: ['Keras', 'ML / AI'],
  'scikit-learn': ['scikit-learn', 'ML / AI'],
  sklearn: ['scikit-learn', 'ML / AI'],
  xgboost: ['XGBoost', 'ML / AI'],
  lightgbm: ['LightGBM', 'ML / AI'],
  catboost: ['CatBoost', 'ML / AI'],
  transformers: ['Transformers', 'ML / AI'],
  'sentence-transformers': ['Sentence-Transformers', 'ML / AI'],
  langchain: ['LangChain', 'ML / AI'],
  langgraph: ['LangGraph', 'ML / AI'],
  'langchain-community': ['LangChain', 'ML / AI'],
  openai: ['OpenAI', 'ML / AI'],
  anthropic: ['Anthropic', 'ML / AI'],
  'llama-index': ['LlamaIndex', 'ML / AI'],
  llama_index: ['LlamaIndex', 'ML / AI'],
  spacy: ['spaCy', 'ML / AI'],
  nltk: ['NLTK', 'ML / AI'],
  'opencv-python': ['OpenCV', 'ML / AI'],
  peft: ['PEFT', 'ML / AI'],
  trl: ['TRL', 'ML / AI'],
  accelerate: ['Accelerate', 'ML / AI'],
  diffusers: ['Diffusers', 'ML / AI'],
  shap: ['SHAP', 'ML / AI'],
  optuna: ['Optuna', 'ML / AI'],
  gymnasium: ['Gymnasium', 'ML / AI'],
  gym: ['Gymnasium', 'ML / AI'],
  'stable-baselines3': ['Stable-Baselines3', 'ML / AI'],
  tavily: ['Tavily', 'ML / AI'],
  'tavily-python': ['Tavily', 'ML / AI'],
  // Data
  pandas: ['Pandas', 'Data'],
  numpy: ['NumPy', 'Data'],
  polars: ['Polars', 'Data'],
  scipy: ['SciPy', 'Data'],
  matplotlib: ['Matplotlib', 'Data'],
  seaborn: ['Seaborn', 'Data'],
  plotly: ['Plotly', 'Data'],
  pyspark: ['PySpark', 'Data'],
  dask: ['Dask', 'Data'],
  // DevOps / MLOps
  mlflow: ['MLflow', 'DevOps'],
  prefect: ['Prefect', 'DevOps'],
  'apache-airflow': ['Airflow', 'DevOps'],
  airflow: ['Airflow', 'DevOps'],
  evidently: ['Evidently', 'DevOps'],
  'prometheus-client': ['Prometheus', 'DevOps'],
  wandb: ['Weights & Biases', 'DevOps'],
  dvc: ['DVC', 'DevOps'],
  // Cloud
  boto3: ['AWS', 'Cloud'],
  awscli: ['AWS', 'Cloud'],
  sagemaker: ['AWS SageMaker', 'Cloud'],
  'google-cloud-storage': ['GCP', 'Cloud'],
  // Mobile
  'react-native': ['React Native', 'Mobile'],
  expo: ['Expo', 'Mobile'],
}

// Strong, distinctive tokens to scan for in README text when manifests are
// missing. Lowercased substring match — only include low-false-positive terms.
export const README_KEYWORDS = {
  fastapi: ['FastAPI', 'Backend'],
  flask: ['Flask', 'Backend'],
  django: ['Django', 'Backend'],
  'next.js': ['Next.js', 'Frontend'],
  nextjs: ['Next.js', 'Frontend'],
  tailwind: ['Tailwind CSS', 'Frontend'],
  streamlit: ['Streamlit', 'Frontend'],
  gradio: ['Gradio', 'Frontend'],
  postgresql: ['PostgreSQL', 'Database'],
  postgres: ['PostgreSQL', 'Database'],
  mongodb: ['MongoDB', 'Database'],
  redis: ['Redis', 'Database'],
  chromadb: ['ChromaDB', 'Database'],
  faiss: ['FAISS', 'Database'],
  pinecone: ['Pinecone', 'Database'],
  pytorch: ['PyTorch', 'ML / AI'],
  tensorflow: ['TensorFlow', 'ML / AI'],
  langchain: ['LangChain', 'ML / AI'],
  langgraph: ['LangGraph', 'ML / AI'],
  huggingface: ['Hugging Face', 'ML / AI'],
  'hugging face': ['Hugging Face', 'ML / AI'],
  transformers: ['Transformers', 'ML / AI'],
  'scikit-learn': ['scikit-learn', 'ML / AI'],
  xgboost: ['XGBoost', 'ML / AI'],
  lightgbm: ['LightGBM', 'ML / AI'],
  deberta: ['DeBERTa', 'ML / AI'],
  qlora: ['QLoRA', 'ML / AI'],
  rag: ['RAG', 'ML / AI'],
  docker: ['Docker', 'DevOps'],
  kubernetes: ['Kubernetes', 'DevOps'],
  mlflow: ['MLflow', 'DevOps'],
  airflow: ['Airflow', 'DevOps'],
  prefect: ['Prefect', 'DevOps'],
  'github actions': ['GitHub Actions', 'DevOps'],
  aws: ['AWS', 'Cloud'],
  sagemaker: ['AWS SageMaker', 'Cloud'],
}

// File-presence signals -> [displayName, category]
export const FILE_SIGNALS = {
  dockerfile: ['Docker', 'DevOps'],
  'docker-compose.yml': ['Docker Compose', 'DevOps'],
  'docker-compose.yaml': ['Docker Compose', 'DevOps'],
  'requirements.txt': ['Python', 'Language'],
  'pyproject.toml': ['Python', 'Language'],
  'go.mod': ['Go', 'Language'],
  'pom.xml': ['Java', 'Language'],
  'build.gradle': ['Gradle', 'DevOps'],
  gemfile: ['Ruby', 'Language'],
  'composer.json': ['PHP', 'Language'],
  'cargo.toml': ['Rust', 'Language'],
}
